### ISSUE TITLE
Better JWT tokens from jwt.comma.ai

### ISSUE THREAD

**Issue by royjr** [commaai/comma-api#24]
Tokens are currently set to expire a year. If a token was to get compromised, one would not be able to do anything about it and would be subject to malicious acts.. snapshots, location, reboots.

A possible solution would be the ability to list tokens along with a revoke option, or simply a revoke all.

Another option is to create shorter lived tokens, but this does not fully solve the issue and leaves a user at risk until its expiration. This also requires recreating tokens more frequently which complicates everything.

**Comment by Madankh** [comment]
Hi do we need to add short lifespam JWT token

**Comment by adeebshihadeh** [comment]
Tokens are now only good for 90 days.
